import { Globe, Mail } from "lucide-react";

export const metadata = {
  title: 'Privacy Policy | kGamify - Gamified Competition Platform',
  description: 'Learn how kGamify protects your privacy and handles your personal data. Read our comprehensive privacy policy covering data collection, usage, and your privacy rights.',
  keywords: 'kGamify privacy policy, data protection, privacy rights, personal data, gamified learning privacy, edtech privacy policy, data security',
  robots: 'index, follow',
  alternates: {
    canonical: 'https://kgamify.in/privacy-policy',
  },
  openGraph: {
    title: 'Privacy Policy | kGamify',
    description: 'Discover how kGamify protects your privacy and personal data. Read our detailed privacy policy for our gamified learning platform.',
    url: 'https://kgamify.in/privacy-policy',
    siteName: 'kGamify',
    images: [
      {
        url: '/privacy_preview.png',
        width: 1200,
        height: 630,
        alt: 'kGamify Privacy Policy',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Privacy Policy | kGamify',
    description: 'Learn about kGamify\'s commitment to privacy and data protection. Read our privacy policy for transparent data handling practices.',
    images: ['/privacy_preview.png'],
  },
  other: {
    'application/ld+json': JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: 'Privacy Policy | kGamify',
      url: 'https://kgamify.in/privacy-policy',
      description: 'Comprehensive privacy policy for kGamify\'s gamified learning platform, detailing data collection, usage, storage, and user privacy rights.',
      publisher: {
        '@type': 'Organization',
        name: 'kGamify',
        url: 'https://kgamify.in',
      },
      mainEntity: {
        '@type': 'LegalDocument',
        name: 'Privacy Policy',
        description: 'Privacy policy governing data collection and usage on kGamify platform',
        publisher: {
          '@type': 'Organization',
          name: 'kGamify',
        },
      },
    }),
  },
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-12">
        <div className="mx-auto max-w-7xl">
          <h1 className="mb-8 text-3xl font-bold text-gray-900">Privacy Policy</h1>

          <div className="prose prose-orange max-w-none">
            <p className="text-gray-700">Effective date: May 10, 2025</p>

            <div className="border-l-4 border-orange-500 my-8 pl-2">
<p>This document is an electronic record in terms of the Information Technology Act, 2000 and the relevant rules under it, including amendments. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>            </div>
            <div className="border-l-4 border-orange-500 my-8 pl-2">
<p>This Privacy Policy is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which requires the publication of privacy policies, terms of use, and rules and regulations for access or usage of the website [<a href="http://www.kgamify.com" className="text-orange-500">www.kgamify.in</a>], including its mobile application (hereinafter referred to as the &ldquo;Platform&rdquo;).</p>            </div>
            <div className="border-l-4 border-orange-500 my-8 pl-2">
<p>The Platform is owned and operated by Yantrikisoft Pvt. Ltd., a private limited company incorporated under the Companies Act, 1956, having its registered office at D207, Shabi Complex, Plot 110-111, Sector 12, Vashi, Navi Mumbai &ndash; 400703, India (hereinafter referred to as &ldquo;Yantrikisoft&rdquo;).</p>            </div>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">1. Introduction</h2>
            <p className="text-gray-700">
              When you use the Platform, we may collect personal and non-personal information such as:
            </p>
            <ul className="list-disc pl-6 text-gray-700">
              <li>Name</li>
              <li>Email address</li>
              <li>Contact number</li>
              <li>Educational background</li>
              <li>Usage behaviour, scores, and performance data</li>
              <li>Device, browser, and IP-related data</li>
            </ul>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">2. How We Use Your Information</h2>
            <p className="text-gray-700">
              Your information may be used in:
            </p>
            <ul className="list-disc pl-6 text-gray-700">
              <li>Register and manage your account</li>
              <li>Facilitate participation in championships</li>
              <li>Provide rewards, discounts, and offers</li>
              <li>Communicate updates, offers, and support messages</li>
              <li>Improve platform functionality through analytics</li>
              <li>Generate employability and knowledge indexes via AI</li>
            </ul>
            <p className="text-gray-700">We do not sell or share your personally identifiable information with third parties for marketing purposes without your consent.</p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">3. Cookies & Tracking</h2>
            <p className="text-gray-700">
              kGamify uses cookies and similar technologies to personalize user experience and understand usage behaviour. You can manage your cookie settings through your browser.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">4. Data Security</h2>
            <p className="text-gray-700">
              We follow industry-standard security practices to protect your personal data. While we strive to safeguard information, no system is completely immune to breaches. Verification may be required to process sensitive requests.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">5. Children’s Privacy</h2>
            <p className="text-gray-700">
              kGamify is not intended for children under 13 years of age. We do not knowingly collect personal information from minors. If found, such data will be deleted immediately.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">6. Information Sharing & Disclosure</h2>
            <p className="text-gray-700">
             We may disclose information:
            </p>
            <ul className="list-disc pl-6 text-gray-700">
              <li>To comply with applicable laws and legal processes</li>
<li>To protect the rights and safety of Yantrikisoft or its users</li>
<li>To trusted partners working on our behalf under confidentiality agreements</li>
            </ul>
            <p className="text-gray-700">We may share aggregated and anonymized data with partners for analytics or business development.</p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">7. Access & Correction</h2>
            <p className="text-gray-700">
             To access, correct, or delete your information, you may contact us via email at:
            </p>
            <div className="flex"><Mail className="mr-2 text-gray-700"/> <a href="mailto:support@kgamify.in">support@kgamify.in</a></div>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">8. Changes to This Policy</h2>
            <p className="text-gray-700">We may update this Privacy Policy periodically. Continued use of the Platform after changes implies acceptance.</p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">9. Contact Us</h2>
            <p className="text-gray-700">
              For any queries or concerns regarding this Privacy Policy, contact us at:
            </p>
            <address className="my-4">
              Yantrikisoft Pvt. Ltd.<br/>D207, Shabi Complex, Plot 110-111, Sector 12, Vashi, Navi Mumbai – 400703, India
            </address>
            <div className="flex items-center my-2"><Mail className="mr-2 text-gray-700" /> <a href="mailto:support@kgamify.in" className="text-gray-700">support@kgamify.in</a></div>
            <div className="flex items-center my-2"><Globe className="mr-2 text-gray-700" /> <a href="https://www.kgamify.in" className="text-gray-700">www.kgamify.in</a></div>
          </div>
        </div>
      </div>
    </div>
  )
}
